version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"   # S3 API portu
      - "9001:9001"   # Yönetim paneli
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
