version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: repsy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: repsy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # Manage Panel
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data:
